### PR TITLE
Fixed multi-cam initialization

### PR DESCRIPTION
**Pull request by normen**
This PR fixes multiple camera initialization, the http server was generated multiple times as the whole configuration was pushed multiple times.

It also adds a throttle of 10s to the event firing so that the message is only sent once every 10 seconds (by default).

Plus the parameters all have default values now.

The "port" parameter is back in the global settings as I think it makes more sense there.

### CODE REVIEW

**Comment by normen** [comment]
Come to think of it, I have some ideas for this plugin so if you don't want to develop it further I could pick up if you want.

**Comment by Samfox2** [comment]
Thank you for your contribution. Multi cam init was on my list but who has more than one door cam :-)

**Comment by normen** [comment]
Well I do :) I'll look into adding the "switch" feature as well, for me its much more convenient to simply link the bell with my actual 433mHz doorbell via a HomeKit automation.

**Comment by Samfox2** [comment]
Sounds great. By the way - I‘m getting a lot of questions about a compiled ffmpeg binary for raspi 3 (guess it‘s your thing). Could you upload your binary and link it in the readme (here and maybe also in KhaosT‘s plugin - I‘m sure he gets the same questions). Thx.

**Comment by normen** [comment]
No, thats illegal. I added info on how to compile to the original plugins wiki, the link is actually in your README :)

**Comment by Samfox2** [comment]
Ok, actually it is not but I will continue to refer to it.

**Comment by normen** [comment]
Ah, true, they solved the licensing issues. Anyway not interested in hosting or supporting a binary in any form :)

**Pull request merged**
